### ISSUE TITLE
Installation failed: The extension is not installable on any currently installed products

### ISSUE THREAD

**Issue by Gimmeaphatbeat** [tunnelvisionlabs/MouseNavigation#13]
![image](https://cloud.githubusercontent.com/assets/7252279/22211100/e72474fa-e183-11e6-82d8-b1f8df594d22.png)

My Visual Studio 'about' window:

![image](https://cloud.githubusercontent.com/assets/7252279/22211181/2a951eba-e184-11e6-90f3-b50136cff71e.png)

Install log:
```
23/01/2017 15:49:43 - Microsoft VSIX Installer
23/01/2017 15:49:43 - -------------------------------------------
23/01/2017 15:49:43 - Initializing Install...
23/01/2017 15:49:44 - Extension Details...
23/01/2017 15:49:44 - 	Identifier      : Tvl.VisualStudio.MouseNavigation.74370A5B-33D9-4F9E-A910-D83D487A825D
23/01/2017 15:49:44 - 	Name            : Mouse Navigation
23/01/2017 15:49:44 - 	Author          : Sam Harwell
23/01/2017 15:49:44 - 	Version         : 4.0.0
23/01/2017 15:49:44 - 	Description     : Add support for mouse navigation buttons (back and forward).
23/01/2017 15:49:44 - 	Locale          : en-US
23/01/2017 15:49:44 - 	MoreInfoURL     : https://github.com/tunnelvisionlabs/MouseNavigation
23/01/2017 15:49:44 - 	InstalledByMSI  : False
23/01/2017 15:49:44 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
23/01/2017 15:49:44 - 
23/01/2017 15:49:44 - 	Supported Products : 
23/01/2017 15:49:44 - 		Microsoft.VisualStudio.Community
23/01/2017 15:49:44 - 			Version : [11.0,16.0)
23/01/2017 15:49:44 - 
23/01/2017 15:49:44 - 	References      : 
23/01/2017 15:49:44 - 
23/01/2017 15:49:44 - Searching for applicable products...
23/01/2017 15:49:44 - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
23/01/2017 15:49:44 - Found installed product - Microsoft Visual Studio Professional 2013
23/01/2017 15:49:44 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
23/01/2017 15:49:44 - Found installed product - Global Location
23/01/2017 15:49:44 - Found installed product - ssms
23/01/2017 15:49:44 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by sharwell** [comment]
Oh delightful. I'll get a new release out today.

So sorry about the trouble.

:memo: Bug *appears* to be caused by VSIXInstaller.exe from Visual Studio 2013 and earlier doesn't understand Community edition. I'll change them to Pro.

**Comment by sharwell** [comment]
@Gimmeaphatbeat Please let me know if the new release works for you. I have many other extensions I need to update in the same way now and want to make sure it really works so I don't have to do it again. 😄

**Comment by Gimmeaphatbeat** [comment]
OK I'll test this in the next hour.

**Comment by Gimmeaphatbeat** [comment]
Yeah it works fine now, thanks!
